### PR TITLE
Fix #204: Return 401 in case authentication fails on mobile API

### LINKED ISSUE #204: Return 401 in case authentication fails on mobile API
In case authentication fails on mobile API, we need to return 401 error code with no additional information. Currently, we return 500 with very specific information about the error.

The issue is caused by [incorrectly subclassing](https://github.com/lime-company/powerauth-webflow/blob/master/powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/PendingOperationListFailedException.java) `PowerAuthAuthenticationException` (I will declare this class as final, so that it is not extended) - inability to download the operation list has nothing to do with authentication - and [handling this exception type](https://github.com/lime-company/powerauth-webflow/blob/master/powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java#L97) in exception handler.

### PR DESCRIPTION
**Pull request by romanstrobl**
Changes:
* Mobile API exceptions extend now MobileAppApiException
* Responses are either 401 (most actions) or 400 (when operation is finished, failed or expired), 500 remains for error during push registration

I kept distinct Exceptions for different endpoints in MobileAppApiController when apiAuthentication object is missing, if you want to unify these Exceptions, we can change it, however it will impact previously agreed API with mToken, which I am waiting with this change for feedback.

### CODE REVIEW

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java [hunk 1]
```diff
@@ -59,7 +59,7 @@
      * @return Response with error details.
      */
     @ExceptionHandler(InvalidRequestObjectException.class)
-    @ResponseStatus(HttpStatus.BAD_REQUEST)
+    @ResponseStatus(HttpStatus.UNAUTHORIZED)
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java]: Why do we throw 401 here? This seems to be `MobileApiException` subclass...

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java [hunk 2]
```diff
@@ -71,7 +71,7 @@
      * @return Response with error details.
      */
     @ExceptionHandler(InvalidActivationException.class)
-    @ResponseStatus(HttpStatus.BAD_REQUEST)
+    @ResponseStatus(HttpStatus.UNAUTHORIZED)
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java]: dtto

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java [hunk 3]
```diff
@@ -83,7 +83,7 @@
      * @return Response with error details.
      */
     @ExceptionHandler(CancelOperationFailedException.class)
-    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+    @ResponseStatus(HttpStatus.UNAUTHORIZED)
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java]: dtto

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java [hunk 4]
```diff
@@ -95,7 +95,7 @@
      * @return Response with error details.
      */
     @ExceptionHandler(PendingOperationListFailedException.class)
-    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+    @ResponseStatus(HttpStatus.UNAUTHORIZED)
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java]: dtto

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java [hunk 5]
```diff
@@ -107,7 +107,7 @@
      * @return Response with error details.
      */
     @ExceptionHandler(SignatureVerificationFailedException.class)
-    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+    @ResponseStatus(HttpStatus.UNAUTHORIZED)
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/MobileTokenApiExceptionResolver.java]: Here, I don't understand why we have the new `SignatureVerificationException`. This is one of the few cases where we should use `PowerAuthAuthenticationException` - it should be thrown when signature validation fails or token auth validation fails...

File: powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/SignatureVerificationFailedException.java [hunk 6]
```diff
@@ -1,13 +1,11 @@
...
 
-import io.getlime.security.powerauth.rest.api.base.exception.PowerAuthAuthenticationException;
-
 /**
  * Exception thrown when signature could not be verified.
  *
  * @author Roman Strobl, roman.strobl@lime-company.eu
  */
-public class SignatureVerificationFailedException extends PowerAuthAuthenticationException {
+public class SignatureVerificationFailedException extends MobileAppApiException {
```
Comment (petrdvorak) [inline powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/exception/SignatureVerificationFailedException.java]: I don't see any need for this exception class.
