### PR TITLE
New QR codes, structured operation data and related changes / fixes

### LINKED ISSUE #357: Update data for offline signature QR codes
See new QR code specification:
https://github.com/lime-company/powerauth-webflow/wiki/Off-line-Signatures-QR-Code

### LINKED ISSUE #358: Implement support for structured operation data
See specification:
https://github.com/lime-company/powerauth-webflow/wiki/Off-line-Signatures-QR-Code

We should add API methods for adding structured operation data to an operation, similar to adding form data to an operation.

### PR DESCRIPTION
**Pull request by romanstrobl**
* Fix #357: Update data for offline signature QR codes
* Fix #358: Implement support for structured operation data
* Implemented configuration for operations in database, added endpoint and client method for retrieving configuration
* AllowedSignatureTypes instance is created based on actual configuration instead of being hardcoded
* Implemented push messages in offline mode, push message code moved to separate service
* Fixed disappearing number of attempts in offline verification
* Updated exception handling, partial fix of #320: Avoid using 50X HTTP status codes in favor of 40X codes
* Fixed validation exception when new operation cancels previous operation
* Updated DDL and initial SQL data
* JavaDoc, tests for operation data builder

### CODE REVIEW

File: powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java [hunk 1]
```diff
@@ -93,13 +90,17 @@ public StepResolutionService(StepDefinitionRepository stepDefinitionRepository,
...
      */
-    public CreateOperationResponse resolveNextStepResponse(CreateOperationRequest request) {
+    public CreateOperationResponse resolveNextStepResponse(CreateOperationRequest request) throws OperationAlreadyExistsException {
         CreateOperationResponse response = new CreateOperationResponse();
         if (request.getOperationId() != null && !request.getOperationId().isEmpty()) {
             // operation ID received from the client, verify that it is available
-            if (operationPersistenceService.getOperation(request.getOperationId()) != null) {
-                throw new IllegalArgumentException("Operation could not be created, operation ID is already used: " + request.getOperationId());
+            try {
+                operationPersistenceService.getOperation(request.getOperationId());
```
Comment (petrdvorak) [inline powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java]: I don't like this pattern very much - we are throwing exception in case everything is correct and ignore exception in case of unusual state. I suggest implementing `bool operationExists(String operationId)` method on repository level and use it to implement this in a bit cleaner manner...

Comment (romanstrobl) [reply powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/service/StepResolutionService.java]: Good idea, I will fix it.

**Comment by romanstrobl** [comment]
Style issue fixed.
