### PR TITLE
Fix #302: Invalid error handling during OAuth 2.0 handshake

### LINKED ISSUE #302: Invalid error handling during OAuth 2.0 handshake
Web Flow should handle "error" and "error_description" query parameters added by Spring security when OAuth 2.0 handshake fails:
https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/AuthorizationEndpoint.java#L367

The redirect logic in Web Flow is handled here:
https://github.com/lime-company/powerauth-webflow/blob/develop/powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java#L167

We should handle the error based on:
https://www.oauth.com/oauth2-servers/authorization/the-authorization-response

We should also clear the context when the error occurs.

### PR DESCRIPTION
**Pull request by romanstrobl**
Added error and error_description query parameters when operation is canceled by user.

### CODE REVIEW

File: powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java [hunk 1]
```diff
@@ -181,7 +185,24 @@ public String cancelAuthentication(HttpServletRequest request, HttpServletRespon
             authenticationManagementService.clearContext();
         }
 
-        return "redirect:" + redirectUri;
+        try {
```
Comment (petrdvorak) [inline powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/controller/HomeController.java]: This is too manual - use `UriComponentsBuilder` instead.

https://docs.spring.io/autorepo/docs/spring-framework/4.3.5.RELEASE/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html

You can use it like this:

```java
final String fixedCallbackUrl = UriComponentsBuilder.fromUriString(callbackUrl)
                            .queryParam("redirectId", redirectId).build()
                            .toUriString();
```

**Comment by romanstrobl** [comment]
This PR is still shown as open, can we close it?

**Comment by romanstrobl** [comment]
Nevermind, previous comment closed the PR.
